#!/usr/bin/env bash
#Bash script that installs a nginx

sudo apt-get -y update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
