#!/usr/bin/env bash
#creates a file with PID
#displays "To infinity and beyond" every two seconds infinitely
# displays: I hate the kill command" on SIGTERM
#"Y U no love me" on SIGINT
#cleans up and exits on SIGQUIT

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
